version: '3.8'

networks:
  gitlab-runner-net:
    driver: bridge

services:
  gitlab-dind:
    image: docker:24.0.5-dind
    privileged: true
    restart: always
    networks:
      - gitlab-runner-net
    volumes:
      - dind-data:/var/lib/docker
      - ./certs:/certs
    environment:
      - DOCKER_TLS_CERTDIR=""
    command: ["--storage-driver=overlay2", "--tls=false"]

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    networks:
      - gitlab-runner-net
    depends_on:
      - gitlab-dind
    volumes:
      - ./config:/etc/gitlab-runner
      - ./certs:/certs
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - DOCKER_HOST=tcp://gitlab-dind:2375
      - DOCKER_TLS_CERTDIR=""
      - CI_SERVER_URL=https://clab.mwihoko.com
      - REGISTRATION_TOKEN=glrt-dPx10xUfg8Xn_Mdir1-dj3Q6MQp1OjEH.01.0w06un0q0
    entrypoint: ["/bin/bash", "/entrypoint.sh"]

volumes:
  dind-data: